services:
  koalawiki:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/koala-wiki
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./repositories:/repositories
      - ./data:/data
    networks:
      - dokploy-network
    pull_policy: always
      
  koalawiki-web:
    environment:
      - NEXT_PUBLIC_API_URL=http://koalawiki:8080
      - API_URL=http://koalawiki:8080
    build:
      context: web/.
      dockerfile: Dockerfile
      args:
        - http_proxy=http://172.17.0.1:7890
        - https_proxy=http://172.17.0.1:7890
        - HTTP_PROXY=http://172.17.0.1:7890
        - HTTPS_PROXY=http://172.17.0.1:7890
        - NEXT_PUBLIC_API_URL=http://koalawiki:8080
        - API_URL=http://koalawiki:8080
    pull_policy: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koalawiki.rule=Host(`one-wiki-nhsyxy-c75629.traefik.me`)"
      - "traefik.http.services.koalawiki.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
